# Generated by Django 4.2.2 on 2023-06-10 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_product', models.CharField(max_length=256)),
                ('image_of_product', models.ImageField(upload_to='')),
                ('measure_of_product', models.CharField(max_length=10)),
                ('amount_of_product', models.IntegerField(default=0)),
                ('cost_of_product', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
